from ui.components.operacion_base import OperacionBaseWidget, DialogoVentaExitosa
from PyQt6.QtWidgets import QVBoxLayout, QHBoxLayout, QGridLayout, QLabel, QFrame
from PyQt6.QtCore import Qt

class PestanaNuevaVenta(OperacionBaseWidget):
    def __init__(self, conexion_db, is_edicion=False, id_presupuesto_edicion=None):
        super().__init__(conexion_db, is_edicion=is_edicion, id_presupuesto_edicion=id_presupuesto_edicion)
        self.tipo_documento_seleccionado = 'VENTA'
        self.chk_descontar.setChecked(True)
        self.chk_descontar.setEnabled(True)
        self.btn_confirmar.setText('Confirmar Venta [F12]')

    def armar_panel_inferior(self, layout):
        ly_b1 = QVBoxLayout()
        ly_b1.setSpacing(4)
        ly_b1.addWidget(self.chk_descontar)
        ly_b1_bot = QHBoxLayout()
        self.input_observaciones.setFixedWidth(200)
        ly_b1_bot.addWidget(self.input_observaciones)
        ly_b1_bot.addStretch()
        ly_b1.addLayout(ly_b1_bot)
        layout.addLayout(ly_b1)
        layout.addStretch()
        ly_b2 = QGridLayout()
        ly_b2.setVerticalSpacing(4)
        ly_b2.setHorizontalSpacing(16)
        lbl_sub = QLabel('Subtotal:')
        lbl_sub.setStyleSheet('color: #64748B; font-weight: 600;')
        ly_b2.addWidget(lbl_sub, 0, 0)
        ly_b2.addWidget(self.lbl_subtotal, 0, 1, Qt.AlignmentFlag.AlignRight)
        ly_desc_ctrl = QHBoxLayout()
        ly_desc_ctrl.addWidget(QLabel('Desc:'))
        ly_desc_ctrl.addWidget(self.input_desc_gral)
        ly_desc_ctrl.addWidget(QLabel('%'))
        ly_b2.addLayout(ly_desc_ctrl, 1, 0)
        ly_b2.addWidget(self.lbl_monto_desc, 1, 1, Qt.AlignmentFlag.AlignRight)
        ly_iva_ctrl = QHBoxLayout()
        ly_iva_ctrl.addWidget(self.chk_iva)
        ly_iva_ctrl.addWidget(self.input_iva_porc)
        ly_iva_ctrl.addWidget(QLabel('%'))
        ly_b2.addLayout(ly_iva_ctrl, 2, 0)
        ly_b2.addWidget(self.lbl_monto_iva, 2, 1, Qt.AlignmentFlag.AlignRight)
        layout.addLayout(ly_b2)
        sep = QFrame()
        sep.setFrameShape(QFrame.Shape.VLine)
        sep.setStyleSheet('color: #E2E8F0;')
        layout.addWidget(sep)
        ly_b3 = QVBoxLayout()
        ly_b3.setAlignment(Qt.AlignmentFlag.AlignVCenter)
        ly_tot_final = QHBoxLayout()
        lbl_tot = QLabel('TOTAL:')
        lbl_tot.setStyleSheet('font-weight: 900; color: #334155; font-size: 16px;')
        ly_tot_final.addWidget(lbl_tot)
        ly_tot_final.addWidget(self.lbl_total, 0, Qt.AlignmentFlag.AlignRight)
        ly_b3.addLayout(ly_tot_final)
        ly_b3.addWidget(self.btn_confirmar)
        layout.addLayout(ly_b3)
